WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Data;
using Data.Access;
using Data.Entities;
using WebApp.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.VisualBasic;
using UrunModel = WebApp.Models.UrunModel;


namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private EFMuzayedeDal _efMuzayedeDal = new EFMuzayedeDal();
        private EFKullaniciDal _efKullaniciDal = new EFKullaniciDal();
        private EFKategoriDal _efKategoriDal = new EFKategoriDal();
        private EFUrunDal _efUrunDal = new EFUrunDal();
        private EFUrunResimDal _efUrunResimDal = new EFUrunResimDal();
        IHttpContextAccessor accessor;
        private SecurityController _securityController;
        public HomeController(ILogger<HomeController> logger, IHttpContextAccessor accessor)
        {
            _logger = logger;
            this.accessor = accessor;
            _securityController = new SecurityController(this.accessor);
        }

        public IActionResult Index()
        {
            
            var model = _efMuzayedeDal.GetAll();
            var sonuc = model.Cast<Muzayede>().ToArray();

            var liste = new List<object>();

            liste.Add(sonuc);


            //Jun 6, 2021 22:15:25     MMMM dd, yyyy HH:mm:ss
            /*  foreach (var muzayede in model)
              {
                  var tarih = muzayede.Date.Split(" ")[0];
                  var saat = muzayede.Date.Split(" ")[1];
                  muzayede.Date = new DateTimeOffset(DateTime.Parse(muzayede.Date)).ToUnixTimeMilliseconds().ToString();
              }
            */
            return View(sonuc);
          
        }

        public IActionResult Galeri()
        {
            ViewBag.Kategoriler = _efKategoriDal.GetAll();
            using (MezatContext db = new MezatContext())
            {
                var modellist = new List<UrunModel>();
                var urunlerlist = db.Urun.ToList();
                foreach (var urun in urunlerlist)
                {
                    var model = new UrunModel();
                    model.urun = urun;
                    model.resim = _efUrunResimDal.GetUrunResim(urun.UrunID);
                    modellist.Add(model);
                }
                return View(modellist);
            }
        }

        public IActionResult Contact()
        {
                ViewBag.Message = "İletişim";
                return View();
        }
        public IActionResult EkspertizFormu()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(Kullanici kullanici)
        {
            var model = _efKullaniciDal.GirisKontrol(kullanici.Kullanicimail, kullanici.Sifre);

            if (model != null)
            {
                var claims = new[] { 
                    new Claim(ClaimTypes.Name, model.KullaniciID.ToString()),
                    new Claim(ClaimTypes.Role, "user")
                };

                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);


                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(identity));
                accessor.HttpContext.User = new ClaimsPrincipal(identity);
               
                var id = accessor.HttpContext.User.Identity.Name;

                return RedirectToAction("Index", "Home");

            }
            return Redirect("Login");
        }
        public IActionResult Login()
        {
                if (!string.IsNullOrEmpty(accessor.HttpContext.User.Identity.Name))
                {
                    return RedirectToAction("index", "Home");
                }
                return View();
            }
        public IActionResult KayitOl()
        {
            return View(new Kullanici());
        }
        [HttpPost]
        public IActionResult KayitOl(Kullanici model)
        {
            if (_efKullaniciDal.GirisKontrol(model.Kullanicimail,model.Sifre) == null)
            {
                _efKullaniciDal.Add(
                    new Kullanici
                    {
                        Kullanicimail = model.Kullanicimail,
                        Sifre = model.Sifre,
                        KullaniciAdi = model.KullaniciAdi,
                        KullaniciAdres = "-",
                        KullaniciSoyadi = model.KullaniciSoyadi,
                        KullaniciTelefon = "-"
                    });
                return RedirectToAction("Login", "Home");
            }
            return View(model);

        }

        [HttpGet]
        public ActionResult LogOut()
        {
            HttpContext.SignOutAsync();
            accessor.HttpContext.User = null;
            //   Session["KullaniciID"] = null;
            // Session.Abandon();//sonlandırmak için sessionları
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/Controllers/MezatController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Data.Access;
using Data.Dtos;
using Newtonsoft.Json;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class MezatController : Controller
    {
        private EFMuzayedeDal _efMuzayedeDal = new EFMuzayedeDal();
        private EFMUrunleriDal _efmUrunleriDal = new EFMUrunleriDal();
        private EFKullaniciPeyDal _efKullaniciPeyDal = new EFKullaniciPeyDal();
        public IActionResult Kontrol(int muzayedeId)
        {
           
            var date = _efMuzayedeDal.Get(x=> x.MuzayedeID == muzayedeId).Date;
            if (DateTime.Compare(DateTime.Now, DateTime.Parse(date)) > 0)
            {
                return RedirectToAction("MuzayedeDetay", new { muzayedeId });
            }
            return RedirectToAction("CanliMuzayede", new { muzayedeId });
        }

        public IActionResult MuzayedeDetay(int muzayedeId)
        {
            var model = _efmUrunleriDal.GetMuzayedeDetay(muzayedeId);
            return View(model);
        }
        public IActionResult CanliMuzayede(int muzayedeId=1)
        {
            var model = _efmUrunleriDal.GetMuzayedeDetay(muzayedeId);
            var list = model.murunler;
            ViewBag.json = JsonConvert.SerializeObject(list);
            return View();
        }

        [HttpPost]
        public string UpdatePey(int murunid)
        {
            var kpey = _efKullaniciPeyDal.UpdateSonPey(4, murunid);
            return JsonConvert.SerializeObject(kpey);
        }
        
        [HttpGet]
        public string GetSonPey(int murunid)
        {
            var kpey = _efKullaniciPeyDal.GetSonpey(murunid);
            return JsonConvert.SerializeObject(kpey);
        }
        [HttpGet]
        public string GetResimler(int urunid)
        {
            var resimler = new EFUrunResimDal().GetUrunResim(urunid);
            return JsonConvert.SerializeObject(resimler);
        }
    }
}

WebApp/Views/Home/Contact.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!-- ======= Contact Section ======= -->
<section id="contact" class="contact">
    <div class="container">
        <div class="section-title">
            <span>Contact</span>
            <h2>Contact</h2>
            <p>Sit sint consectetur velit quisquam cupiditate impedit suscipit alias</p>
        </div>
    </div>

    <div class="map">
        <iframe style="border:0; width: 100%; height: 350px;" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621" frameborder="0" allowfullscreen></iframe>
    </div>

    <div class="container">

        <div class="info-wrap mt-5">
            <div class="row">
                <div class="col-lg-4 info">
                    <i class="ri-map-pin-line"></i>
                    <h4>Location:</h4>
                    <p>A108 Adam Street<br>New York, NY 535022</p>
                </div>

                <div class="col-lg-4 info mt-4 mt-lg-0">
                    <i class="ri-mail-line"></i>
                    <h4>Email:</h4>
                    <p>info@example.com<br>contact@example.com</p>
                </div>

                <div class="col-lg-4 info mt-4 mt-lg-0">
                    <i class="ri-phone-line"></i>
                    <h4>Call:</h4>
                    <p>+1 5589 55488 51<br>+1 5589 22475 14</p>
                </div>
            </div>
        </div>

        <form action="~/MyBiz/forms/contact.php" method="post" role="form" class="php-email-form">
            <div class="form-row">
                <div class="col-md-6 form-group">
                    <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                    <div class="validate"></div>
                </div>
                <div class="col-md-6 form-group">
                    <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                    <div class="validate"></div>
                </div>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                <div class="validate"></div>
            </div>
            <div class="form-group">
                <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
                <div class="validate"></div>
            </div>
            <div class="mb-3">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Your message has been sent. Thank you!</div>
            </div>
            <div class="text-center"><button type="submit">Send Message</button></div>
        </form>

    </div>
</section><!-- End Contact Section -->

WebApp/Views/Home/EkspertizFormu.cshtml
<section>
    <div class="content">

        <div class="container" style="background-color: beige">
            <div class="row align-items-stretch justify-content-center no-gutters">
                <div class="col-md-7">
                    <div class="form h-100 contact-wrap p-5">
                        <h3 class="text-center" style="color: dodgerblue">Ekspertiz Formu</h3>
                        <form class="mb-5" method="post" id="contactForm" name="contactForm">
                            <div class="row">
                                <div class="col-md-6 form-group mb-3">
                                    <label for="" class="col-form-label">Name *</label>
                                    <input type="text" class="form-control" name="name" id="name" placeholder="Your name">
                                </div>
                                <div class="col-md-6 form-group mb-3">
                                    <label for="" class="col-form-label">Email *</label>
                                    <input type="email" class="form-control" name="email" id="email" placeholder="Your email">
                                </div>
                            </div>

                            <p>          ~ Görsel boyutlarının her biri en fazla 5 MB olabilir.</p>
                            <p>          ~ Dosya uzantıları jpg olmalıdır.</p>
                            <div class="row align-content-lg-center">
                                <form action="~/MyBiz/gonder.php" method="POST" enctype="multipart/form-data">
                                    <div style="padding: 10px">

                                        <label for="dosya"> Yüklenecek dosyayı seçiniz:</label> <br />
                                        <input type="file" name="dosya" id=""> <br>
                                    </div>
                                    <div>
                                        <input class="genric-btn danger" type="submit" value="Yükle">
                                    </div>
                                </form>
                                &nbsp;

                                <p>
                                    Gönder butonuna tıkaldığınızda Kişisel Verilerin Korunması'nı kabul etmiş sayısılırsınız.
                                </p>
                            </div>

                            <div class="row mb-5">
                                <div class="col-md-12 form-group mb-3">
                                    <label for="message" class="col-form-label">Message *</label>
                                    <textarea class="form-control" name="message" id="message" cols="30" rows="4" placeholder="Write your message"></textarea>
                                </div>
                            </div>
                            <div class="row justify-content-center">
                                <div class="col-md-5 form-group text-center">
                                    <input type="submit" value="Send Message" class="btn btn-block btn-primary rounded-0 py-2 px-4">
                                    <span class="submitting"></span>
                                </div>
                            </div>
                        </form>

                        <div id="form-message-warning mt-4"></div>
                        <div id="form-message-success">
                            Your message was sent, thank you!
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>
</section>

WebApp/Views/Home/Galeri.cshtml
@{
    ViewBag.Title = "Urunler";
}
@model List<UrunModel>
<section id="portfolio" class="portfolio">
    <div class="container">

        <div class="section-title">
            <span>Kategoriler</span>
            <h2>Kategoriler</h2>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <ul id="portfolio-flters">
                    @foreach (var kategori in ViewBag.Kategoriler)
                    {
                        <li data-filter=".filter-app"><a href="#">@kategori.KategoriAdi</a></li>
                    }
                </ul>
            </div>
        </div>
    </div>
</section><!-- End Portfolio Section -->
<section id="team" class="team">
    <div class="container">

        <div class="row">

        @foreach (var urunModel in Model)
        {
            <div class="col-lg-6 mt-4">
                <div class="member d-flex align-items-start">
                    <div class="pic" style="width: 100px; height: 100px">
                        
                            @foreach (var image in urunModel.resim)
                            {
                                
                                    <a>
                                        <img  src="@image.Base64" class="img-fluid" alt="Red dot" >
                                    </a>

                               
                            }
                        
                        @*<marquee behavior="scroll" direction="right" scrollamount="30">
            <img src="@Url.Content(urunModel.resim)" width="72" height="79" alt="Flying Bee">
        </marquee>
        <img src="@urunModel.resim[0].Base64" class="img-fluid" alt="Red dot">*@
                    </div>
                    <div class="member-info">
                        <h4>@urunModel.urun.UrunAdi</h4>
                        <p>@urunModel.urun.UrunAciklamasi</p>
                        <span>@urunModel.urun.UrunFiyat</span>
                        <div class="social">
                            <a href=""><i class="ri-twitter-fill"></i></a>
                            <a href=""><i class="ri-facebook-fill"></i></a>
                            <a href=""><i class="ri-instagram-fill"></i></a>
                            <a href=""> <i class="ri-linkedin-box-fill"></i> </a>
                        </div>
                    </div>
                </div>
            </div>
        }
        </div>

    </div>
</section><!-- End Team Section -->

WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Data.Entities.Muzayede[]


<div class="container-fluid  ">
    <div class="row ">
        <div class="col-md-6">
            &nbsp;
            <div class="card ">
                <div class="card-body text-center">
                    <img src="~/MyBiz/img/muzayede.png" width="80%" height="150px">

                    <p></p>

                    <!-- Start exclusive deal Area -->
                    <section class="exclusive-deal-area">
                        <div class="container-fluid">
                            <div class="row justify-content-center align-items-center">
                                <div class="row clock_sec clockdiv" id="clockdiv">
                                    <div class="col-lg-12">
                                        <h1> <span class="badge badge-secondary">@Model[0].MuzayedeAdi Müzayedesi</span></h1>
                                    </div>
                                    <div class="col-lg-12">

                                        <p id="@Model[0].MuzayedeID"></p>
                                        <script>
                                                    var dist = -1;
                                                    var x = setInterval(function() {

                                                        // If the count down is over, write some text
                                                        if (dist < 0) {
                                                            document.getElementById("btn_@Model[0].MuzayedeID").value = "Canlı";
                                                            document.getElementById("btn_@Model[0].MuzayedeID").className += " btn-success";
                                                            document.getElementById("@Model[0].MuzayedeID").innerHTML = "Müzayede Başladı";
                                                            if (dist < -50000) {
                                                                clearInterval(x);
                                                                document.getElementById("btn_@Model[0].MuzayedeID").value = "Sonucları Gör";
                                                                document.getElementById("btn_@Model[0].MuzayedeID").className += " btn-primary";
                                                            document.getElementById("@Model[0].MuzayedeID").innerHTML = "Müzayede Sona ermiştir.";
                                                            }
                                                        }
                                                    },1000);
                                        </script>
                                    </div>
                                </div>
                                <input id="btn_@Model[0].MuzayedeID" class="btn-lg " type="submit" onClick="location.href = '@Url.Action("CanliMuzayede","Mezat",new { muzayedeId = Model[0].MuzayedeID })'" value='İncele'>

                            </div>

                        </div>

                    </section>
                    <!-- End exclusive deal Area -->
                </div>
            </div>


        </div>
        @for (int i = 1; i < Model.Length; i++)
        {
            <div class="col-md-6">
                &nbsp;
                <div class="card ">
                    <div class="card-body text-center">
                        <img src="~/MyBiz/img/muzayede.png" width="80%" height="150px">

                        <p></p>

                        <!-- Start exclusive deal Area -->
                        <section class="exclusive-deal-area">
                            <div class="container-fluid">
                                <div class="row justify-content-center align-items-center">
                                    <div class="row clock_sec clockdiv" id="clockdiv">
                                        <div class="col-lg-12">
                                            <h1> <span class="badge badge-secondary">@Model[i].MuzayedeAdi Müzayedesi</span></h1>
                                        </div>
                                        <div class="col-lg-12">

                                            <p id="@Model[i].MuzayedeID"></p>
                                            <script>

                                                var x = setInterval(function() {

                                                        var distance = new Date("@Model[i].Date").getTime() - new Date().getTime();

                                                        var days = Math.floor(distance / (1000 * 60 * 60 * 24));
                                                        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                                                        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
                                                        var seconds = Math.floor((distance % (1000 * 60)) / 1000);

                                                        console.log("@Model[i].Date" + " " + distance + " " + "@Model[i].MuzayedeID");
                                                        // Output the result in an element with id="demo"
                                                        document.getElementById("@Model[i].MuzayedeID").innerHTML = days + "d " + hours + "h " + minutes + "m " + seconds + "s ";

                                                        // If the count down is over, write some text
                                                        if (distance < 0) {
                                                            document.getElementById("btn_@Model[i].MuzayedeID").value = "Canlı";
                                                            document.getElementById("btn_@Model[i].MuzayedeID").className += " btn-success";
                                                            document.getElementById("@Model[i].MuzayedeID").innerHTML = "Müzayede Başladı";
                                                            if (distance < -50000) {
                                                                clearInterval(x);
                                                                document.getElementById("btn_@Model[i].MuzayedeID").value = "Sonucları Gör";
                                                                document.getElementById("btn_@Model[i].MuzayedeID").className += " btn-primary";
                                                                document.getElementById("@Model[i].MuzayedeID").innerHTML = "Müzayede Sona ermiştir.";
                                                            }
                                                        }
                                                    },
                                                    1000);
                                            </script>
                                        </div>
                                    </div>
                                    <input id="btn_@Model[i].MuzayedeID" class="btn-lg btn-primary" type="submit" onClick="location.href = '@Url.Action("Kontrol", "Mezat", new {muzayedeId = Model[i].MuzayedeID})'" value='İncele'>

                                </div>

                            </div>

                        </section>
                        <!-- End exclusive deal Area -->
                    </div>
                </div>


            </div>

        }
    </div>

</div>

WebApp/Views/Home/KayitOl.cshtml
@model Data.Entities.Kullanici
    <section>
        <div class="content">

            <div class="container" style="background-color: beige">
        <div class="row align-items-stretch justify-content-center no-gutters">
            <div class="col-md-7">
                <div class="form h-100 contact-wrap p-5">
                    <h3 class="text-center" style="color: dodgerblue">Üyelik işlemleri</h3>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <center>
                        <form class="col-md-12 align-items-center" action="/Home/KayitOl" method="post" id="contactForm" novalidate="novalidate">
                            <div class="row">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="col-md-12 form-group align-items-center">
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.KullaniciAdi, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(m => m.KullaniciAdi, new { htmlAttributes = new { @class = "form-control", @type = "isim", placeholder = "İsim" } })
                                            @Html.ValidationMessageFor(m => m.KullaniciAdi, "", new { @class = "text-danger" })
                                            <div class="valid-feedback">
                                                Looks good!
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12 form-group align-items-center">
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.KullaniciSoyadi, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(m => m.KullaniciSoyadi, new { htmlAttributes = new { @class = "form-control", @type = "soyisim", placeholder = "Soyisim" } })
                                            @Html.ValidationMessageFor(m => m.KullaniciSoyadi, "", new { @class = "text-danger" })
                                            <div class="valid-feedback">
                                                Looks good!
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12 form-group align-items-center">
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.Kullanicimail, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(m => m.Kullanicimail, new { htmlAttributes = new { @class = "form-control", @type = "email", placeholder = "Email" } })
                                            @Html.ValidationMessageFor(m => m.Kullanicimail, "", new { @class = "text-danger" })
                                            <div class="valid-feedback">
                                                Looks good!
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12 form-group align-items-center">
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.Sifre, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(m => m.Sifre, new { htmlAttributes = new { @class = "form-control", @type = "password", placeholder = "Password" } })
                                            @Html.ValidationMessageFor(m => m.Sifre, "", new { @class = "text-danger" })
                                            <div class="valid-feedback">
                                                Looks good!
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-12 align-items-center">
                                <div style="padding-left:0px">
                                    <div class="form-group">

                                        <input type="checkbox" id="f-option2" name="selector">
                                        <label for="f-option2">Müzayede Kuralları, Kullanıcı Sözleşmesi, Gizlilik Politikası ve Kişisel Verilerin Korunması' nı kabul ediyorum .</label>

                                    </div>
                                </div>
                            </div>
                            &nbsp;

                            <div class="form-group align-items-center">
                                <button class="btn btn-primary" type="submit">Sign Up</button>

                            </div>

                            <div class="align-items-center">
                                <a class="already" href="#">You already have an account? Login here.</a>
                            </div>



                        </form>
                        </center>


                    }
                </div>
            </div>
            </div>
            </div>
        </div>
    </section>

 